#!/usr/bin/env python3
"""Scan model fixtures and report unary-backend coverage via --unary-audit."""

from __future__ import annotations

import csv
import subprocess
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BIN = ROOT / "target" / "release" / "opendefalgsplitting"
OUT_DIR = ROOT / "docs" / "ablation"
CSV_PATH = OUT_DIR / "results_unary_audit.csv"
SUMMARY_PATH = OUT_DIR / "unary_audit_summary.txt"
TEX_PATH = Path(__file__).resolve().parents[2] / "qfdef" / "companion" / "appendix" / "C-unary-audit.tex"

MODEL_GLOBS = [
    ROOT / "model_examples" / "*.model",
    ROOT / "testing" / "tests_definibilidad" / "fixtures" / "*.model",
]


def discover_models() -> list[Path]:
    seen: set[Path] = set()
    out: list[Path] = []
    for pattern in MODEL_GLOBS:
        for path in sorted(pattern.parent.glob(pattern.name)):
            rp = path.resolve()
            if rp not in seen:
                seen.add(rp)
                out.append(rp)
    return out


def ensure_binary() -> None:
    if BIN.is_file():
        return
    print("Building release binary...", file=sys.stderr)
    subprocess.run(
        ["cargo", "build", "--release"],
        cwd=ROOT,
        check=True,
    )


def run_audit(models: list[Path]) -> list[dict[str, str]]:
    if not models:
        return []
    cmd = [str(BIN), "--unary-audit", *[str(p) for p in models]]
    proc = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, check=True)
    lines = [ln for ln in proc.stdout.splitlines() if ln.strip()]
    if len(lines) <= 1:
        return []
    reader = csv.DictReader(lines)
    return list(reader)


def write_summary(rows: list[dict[str, str]]) -> str:
    unary_rows = [r for r in rows if r.get("arity") == "1"]
    decisions = Counter(r.get("unary_decision", "?") for r in unary_rows)
    early = sum(1 for r in unary_rows if r.get("would_early_exit") == "true")
    lines = [
        f"models_scanned={len({r['model'] for r in rows})}",
        f"targets_total={len(rows)}",
        f"unary_targets={len(unary_rows)}",
        f"early_exit_count={early}",
    ]
    for key in sorted(decisions):
        lines.append(f"decision_{key}={decisions[key]}")
    return "\n".join(lines) + "\n"


def write_tex(rows: list[dict[str, str]], summary: str) -> None:
    counts = {}
    for line in summary.splitlines():
        if "=" in line:
            k, v = line.split("=", 1)
            counts[k] = v

    TEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    with TEX_PATH.open("w", encoding="utf-8") as f:
        f.write("% Auto-generated by scripts/analyze_unary_backend.py\n")
        f.write("\\begin{table}[ht]\n\\centering\n")
        f.write("\\caption{Unary-backend audit summary (extended fixture cohort).}\n")
        f.write("\\label{tab:unary-audit}\n")
        f.write("\\begin{tabular}{@{}lr@{}}\n\\toprule\n")
        f.write("Metric & Value \\\\\n\\midrule\n")
        f.write(f"Models scanned & {counts.get('models_scanned', '0')} \\\\\n")
        f.write(f"Target relations & {counts.get('targets_total', '0')} \\\\\n")
        f.write(f"Arity-1 targets & {counts.get('unary_targets', '0')} \\\\\n")
        f.write(f"Early exit (Def/Reject) & {counts.get('early_exit_count', '0')} \\\\\n")
        f.write(f"Skip (arity $\\ne 1$ or mixed arities) & ")
        f.write(f"{counts.get('decision_Skip', '0')} \\\\\n")
        f.write(f"NotDefinable & {counts.get('decision_NotDefinable', '0')} \\\\\n")
        f.write(f"Definable & {counts.get('decision_Definable', '0')} \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n\n")
        f.write("\\small\n\\begin{longtable}{@{}p{0.36\\linewidth}p{0.10\\linewidth}p{0.14\\linewidth}p{0.12\\linewidth}p{0.20\\linewidth}@{}}\n")
        f.write("\\toprule\nModel & Target & Decision & Early & Notes \\\\\n\\midrule\n\\endhead\n")
        for row in rows:
            if row.get("arity") != "1":
                continue
            model = row["model"].replace("_", "\\_")
            if len(model) > 42:
                model = "..." + model[-39:]
            target = row.get("target", "")
            decision = row.get("unary_decision", "")
            early = "yes" if row.get("would_early_exit") == "true" else "no"
            reason = row.get("reason", "").replace("_", "\\_")
            if len(reason) > 28:
                reason = reason[:25] + "..."
            f.write(f"{model} & {target} & {decision} & {early} & {reason} \\\\\n")
        f.write("\\bottomrule\n\\end{longtable}\n")


def main() -> int:
    ensure_binary()
    models = discover_models()
    rows = run_audit(models)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    if rows:
        with CSV_PATH.open("w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=rows[0].keys())
            writer.writeheader()
            writer.writerows(rows)
    summary = write_summary(rows)
    SUMMARY_PATH.write_text(summary, encoding="utf-8")
    write_tex(rows, summary)
    print(summary, end="")
    print(f"CSV -> {CSV_PATH}")
    print(f"TEX -> {TEX_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
